import { createElement } from 'lwc';
import Lwc_2604_eg1_player from 'c/lwc_2604_eg1_player';

describe('c-lwc-2604-eg1-player', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-2604-eg1-player', {
            is: Lwc_2604_eg1_player
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});